// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c481f75c5beef9cc5596b8e630010422)
declare namespace Cloudflare {
	interface Env {
		UPTIME: KVNamespace;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
